# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27cbdd9b0596e80c88e8052470f5be190c84d2422b87e604c17783082b22b35a5b70dd9f3dd3930e2e6a11e1c7a8b999b097207d396733800e58a2cb990db325

test:
  secret_key_base: 3781b970af694f7c22d8e56d78a2f659c7f38386be0437277b684f7972319fa4799f6554c6b21f4070b024ddd2e20fab8e7e0d5027c708a0d6076e329b9d7af9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
